###############################
# BUILD FOR LOCAL DEVELOPMENT #
###############################
FROM node:18-alpine As development

WORKDIR /usr/src/app

RUN npm install --location=global nest

USER node
